---
- name: wait until ssh is available on all nodes
  hosts:
    - ignition
    # - haproxy
  gather_facts: no
  tasks:
    - name: wait until ssh is available
      wait_for_connection:
        delay: 0
        timeout: 300
      retries: 10
